# Generated by Django 4.2.7 on 2023-11-12 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(max_length=200)),
                ('degree_type', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('semester_duration', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=200)),
                ('tuition', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('GERMAN', 'GERMAN')], default='ENGLISH', max_length=50)),
                ('mode_of_study', models.CharField(max_length=200)),
                ('institution_type', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['universities'],
            },
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship', models.CharField(max_length=5000, null=True)),
                ('summer', models.CharField(max_length=5000, null=True)),
                ('winter', models.CharField(max_length=5000, null=True)),
                ('english_language', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=10)),
                ('german_language', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=10)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program', to='website_api.allprograms')),
            ],
            options={
                'ordering': ['program'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='website_api.coursedetails')),
            ],
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WinterOptional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter_op_topics', models.CharField(max_length=5000)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winter_optional', to='website_api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Winter',
            fields=[
                ('winter_id', models.AutoField(primary_key=True, serialize=False)),
                ('winter_topics', models.CharField(max_length=5000)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winter_topics', to='website_api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=5000)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_details', to='website_api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_s_topics', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_semester', to='website_api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Supplementary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplementary', models.CharField(max_length=2000)),
                ('course_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplementary', to='website_api.coursedetails')),
            ],
        ),
        migrations.CreateModel(
            name='SummerOptional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summer_op_topics', models.CharField(max_length=5000)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summer_optional', to='website_api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Summer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summer_topics', models.CharField(max_length=5000)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summer_topics', to='website_api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='InternationalElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_element', models.CharField(max_length=2000)),
                ('course_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='international_element', to='website_api.coursedetails')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ass_type', models.CharField(max_length=2000)),
                ('course_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_type', to='website_api.coursedetails')),
            ],
        ),
        migrations.AddField(
            model_name='allprograms',
            name='universities',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website_api.universities'),
        ),
    ]
