# Generated by Django 4.2.6 on 2023-12-02 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllPrograms',
            fields=[
                ('program_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('program_type', models.CharField(max_length=200)),
                ('degree_type', models.CharField(max_length=200)),
                ('field_of_study', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('duration', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='1', max_length=200)),
                ('tuition', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('ENGLISH', 'ENGLISH'), ('GERMAN', 'GERMAN')], default='ENGLISH', max_length=50)),
                ('mode_of_study', models.CharField(max_length=200)),
                ('institution_type', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['uni_id'],
            },
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('course_details_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('internship', models.CharField(max_length=5000, null=True)),
                ('summer', models.CharField(max_length=5000, null=True)),
                ('winter', models.CharField(max_length=5000, null=True)),
                ('english_language', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=10)),
                ('german_language', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=10)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_details', to='website_api.allprograms')),
            ],
            options={
                'ordering': ['course_details_id'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('org_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('top_details', models.CharField(max_length=2000)),
                ('course_details', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='website_api.coursedetails')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('part_time_employment', models.CharField(max_length=3000)),
                ('accommodation', models.CharField(max_length=3000)),
                ('general_intl_student_support', models.CharField(max_length=3000)),
                ('program_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='website_api.allprograms')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('user_type', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='MALE', max_length=10)),
                ('registration_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WinterTopics',
            fields=[
                ('winter_id', models.AutoField(primary_key=True, serialize=False)),
                ('winter_topics', models.CharField(max_length=5000)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winter_topics', to='website_api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='WinterOptional',
            fields=[
                ('wint_opt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('winter_op_topics', models.CharField(max_length=5000)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winter_optional', to='website_api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('uni_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=500, unique=True)),
                ('university_image', models.FileField(upload_to='images/')),
                ('user_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='website_api.users')),
            ],
        ),
        migrations.CreateModel(
            name='ThirdSemester',
            fields=[
                ('third_sem_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('third_s_topics', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_semester', to='website_api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('support_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('support', models.CharField(max_length=1000)),
                ('service_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support', to='website_api.service')),
            ],
        ),
        migrations.CreateModel(
            name='Supplementary',
            fields=[
                ('sup_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('supplementary', models.CharField(max_length=2000)),
                ('course_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplementary', to='website_api.coursedetails')),
            ],
        ),
        migrations.CreateModel(
            name='SummerTopics',
            fields=[
                ('sum_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summer_topics', models.CharField(max_length=5000)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summer_topics', to='website_api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SummerOptionalTopics',
            fields=[
                ('sum_opt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('summer_op_topics', models.CharField(max_length=5000)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summer_optionals', to='website_api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('req_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('program_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirement', to='website_api.allprograms')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageRequirement',
            fields=[
                ('lang_req_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language_requirement', models.CharField(max_length=2000)),
                ('req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_requirement', to='website_api.requirement')),
            ],
        ),
        migrations.CreateModel(
            name='InternationalElement',
            fields=[
                ('int_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('int_element', models.CharField(max_length=2000)),
                ('course_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='international_element', to='website_api.coursedetails')),
            ],
        ),
        migrations.CreateModel(
            name='ELearning',
            fields=[
                ('e_learn_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('online_course', models.CharField(max_length=10)),
                ('e_learning_description', models.CharField(max_length=2000)),
                ('e_learning_participation', models.CharField(max_length=10)),
                ('ects_availability', models.CharField(max_length=10)),
                ('sign_up_availability', models.CharField(max_length=10)),
                ('program_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='e_learning', to='website_api.allprograms')),
            ],
        ),
        migrations.CreateModel(
            name='CostFunding',
            fields=[
                ('cost_f_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tuition_fee', models.CharField(max_length=1000)),
                ('semester_contribution', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cost_of_living', models.CharField(max_length=2000)),
                ('funding_opportunities', models.CharField(max_length=2000)),
                ('funding_description', models.CharField(max_length=2000)),
                ('program_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_funding', to='website_api.allprograms')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('ass_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ass_type', models.CharField(max_length=2000)),
                ('course_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_type', to='website_api.coursedetails')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationDeadline',
            fields=[
                ('app_d_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('application_deadline', models.CharField(max_length=2000)),
                ('req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_requirement', to='website_api.requirement')),
            ],
        ),
        migrations.AddField(
            model_name='allprograms',
            name='uni_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_programs', to='website_api.universities'),
        ),
        migrations.CreateModel(
            name='AcademicRequirement',
            fields=[
                ('acad_req_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('admission_requirement', models.CharField(max_length=2000)),
                ('req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_requirement', to='website_api.requirement')),
            ],
        ),
    ]
