# Generated by Django 4.2.6 on 2023-12-29 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlinelearning',
            old_name='course_details_id',
            new_name='online_program_id',
        ),
    ]
