# Generated by Django 4.2.6 on 2023-12-08 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WinterOptional',
            new_name='WinterOptionalTopics',
        ),
        migrations.AlterField(
            model_name='applicationdeadline',
            name='req_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_deadline', to='website_api.requirement'),
        ),
    ]
