# Generated by Django 4.2.6 on 2023-12-28 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allprograms',
            name='uni_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='all_programs', to='website_api.universities'),
        ),
    ]
