# Generated by Django 4.2.6 on 2023-12-10 19:57

from django.db import migrations, models
import website_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('website_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universities',
            name='university_image',
            field=models.ImageField(default=None, upload_to=website_api.models.Universities.upload_photo),
        ),
    ]
