# Generated by Django 4.2.6 on 2023-12-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_api', '0004_remove_onlinelearning_online_program_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmenttype',
            name='course_details_id',
        ),
        migrations.RemoveField(
            model_name='internationalelement',
            name='course_details_id',
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='assessment_type',
            field=models.ManyToManyField(related_name='course_details', to='website_api.assessmenttype'),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='international_element',
            field=models.ManyToManyField(related_name='course_details', to='website_api.internationalelement'),
        ),
    ]
