# Generated by Django 4.2.6 on 2023-12-30 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_api', '0005_remove_assessmenttype_course_details_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProgramDetails',
            new_name='Programs',
        ),
    ]
