# Generated by Django 4.2.6 on 2023-12-30 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_api', '0006_rename_programdetails_programs'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineLearningElement',
            fields=[
                ('online_learning_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('online_learning_element', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='onlinelearning',
            old_name='online_learning_id',
            new_name='online_program_id',
        ),
        migrations.AddField(
            model_name='onlinelearning',
            name='attendance_phase_in_Nigeria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlinelearning',
            name='online_adaptability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlinelearning',
            name='pace_of_course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='onlinelearning',
            name='program_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='online_learning', to='website_api.programs'),
        ),
        migrations.AddField(
            model_name='onlinelearning',
            name='type_of_online_learning',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='onlinelearning',
            name='online_learning',
        ),
        migrations.DeleteModel(
            name='OnlineProgram',
        ),
        migrations.AddField(
            model_name='onlinelearning',
            name='online_learning',
            field=models.ManyToManyField(related_name='online_learning', to='website_api.onlinelearningelement'),
        ),
    ]
