# Generated by Django 4.2.6 on 2024-01-09 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_api', '0009_rename_learning_element_onlinelearning_learning_elements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningelement',
            old_name='learning_element',
            new_name='learning_elements',
        ),
    ]
