# Generated by Django 4.2.6 on 2024-01-18 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_api', '0010_rename_learning_element_learningelement_learning_elements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costfunding',
            name='school_fee',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='costfunding',
            name='tuition_fee',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='diploma_supplement',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='integrated_internship',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='coursedetails',
            name='integrated_language',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='onlinelearning',
            name='program_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_learning', to='website_api.programs'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='combine_master_phd',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='overview',
            name='joint_degree_program',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='overview',
            name='school_fee',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='overview',
            name='tuition_fee',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_role',
            field=models.CharField(max_length=50),
        ),
    ]
